### ISSUE TITLE
[Bug 反馈] 回声洞判断相似问题

### ISSUE THREAD

**Issue by HOStudio123** [Moonlark-Dev/Moonlark#109]
### 描述

![Image_1721178727558](https://github.com/user-attachments/assets/ac42a020-319d-4b8b-ae97-c80181c0b7e5)
直接看图图片吧

### 重现步骤

你再投稿一下我的图片

### 截图
在上面

**Comment by This-is-XiaoDeng** [comment]
![图片](https://github.com/user-attachments/assets/432d35ec-21ed-4a6e-adfd-f2940c6e7fd8)

希望[这些更改][1]能解决问题

[1]: https://github.com/Moonlark-Dev/Moonlark/pull/108/files#diff-a45ea5ecce9ba06378d3dcb5d90591bbee2ae921a09016a34bfcbef4ee7f178bR45

**Comment by This-is-XiaoDeng** [comment]
这些更改已随 #108 合并到主分支

**Comment by HOStudio123** [comment]
收到
