### ISSUE TITLE
[新功能提案] Quick-math 建议积分保存，可以兑复活卡

### ISSUE THREAD

**Issue by HOStudio123** [Moonlark-Dev/Moonlark#136]
### 描述

如题

### 原因

你玩过Quick-Math 就知道了

**Comment by This-is-XiaoDeng** [comment]
~~您是否可以发布一个 PR 实现它~~

**Comment by HOStudio123** [comment]
首先我是真的不知道代码结构

**Comment by This-is-XiaoDeng** [comment]
> 首先我是真的不知道代码结构

您可以查阅[我们的文档](https://moonlark-docs.itcdt.top)

**Comment by This-is-XiaoDeng** [comment]
目前技术上比较难实现，可能需要移动大量代码，暂时搁置。

**Comment by This-is-XiaoDeng** [comment]
#### 提议

在失败时添加一个提示 `是否花费 xx vim 复活 [y/N]`，在一定时间内输入 `y` 则继续进行答题。其中 `xx` 会随着使用累计次数和答题深度增加而增加。（默认关闭此提示，可使用 `/quick-math respawn enable` 启用）

**Comment by HOStudio123** [comment]
我觉得行

**Comment by HOStudio123** [comment]
> #### 提议
> 
> 在失败时添加一个提示 `是否花费 xx vim 复活 [y/N]`，在一定时间内输入 `y` 则继续进行答题。其中 `xx` 会随着使用累计次数和答题深度增加而增加。（默认关闭此提示，可使用 `/quick-math respawn enable` 启用）

我觉得行()
