### ISSUE TITLE
[新功能提案] 好友开场白与 OneBot V11 适配器加好友自动同意

### ISSUE THREAD

**Issue by This-is-XiaoDeng** [Moonlark-Dev/Moonlark#178]
### 描述

在 OneBot V11 适配器中自动同意已注册且好感度 `>=0.005` 的用户的好友请求。并在 QQ 和 OneBot V11 适配器添加好友后发送一段开场白。

### 原因

方便私聊使用

**Comment by This-is-XiaoDeng** [comment]
@YifanZhuZhu 文案来处理下

**Comment by YifanZhuZhu** [comment]
.
好久没用github了
