### ISSUE TITLE
[Bug] 头像无法同步更新

### ISSUE THREAD

**Issue by HOStudio123** [Moonlark-Dev/Moonlark#183]
### 描述

qq头像更新之后不能同步dc，包括名称

### 重现步骤

(更新头像或名称)
![Screenshot_20240821_205903_com discord](https://github.com/user-attachments/assets/c8d7290e-477e-4db7-a6c3-0e97a324bec7)

### 截图

![Screenshot_20240821_205909_com tencent mobileqq](https://github.com/user-attachments/assets/22b4016f-26e4-4c52-99e7-009e5b8ba4b7)
![Screenshot_20240821_205903_com discord](https://github.com/user-attachments/assets/d6d8de88-53fe-45d6-b6c9-6da2af09b109)

**Comment by HOStudio123** [comment]
名称同步了，但是头像还是没有

**Comment by xxtg666** [comment]
首先，这是腾讯的缓存问题，等一会就好了
其次，转发的问题请去我的仓库交 issue
https://github.com/xxtg666/nonebot-plugin-discord-message-bridge

**Comment by HOStudio123** [comment]
好，感谢
