### ISSUE TITLE
[新功能提案] Manual copy

### ISSUE THREAD

**Issue by muderstar** [Moonlark-Dev/Moonlark#224]
### 描述

每隔一段时间发送一个图片，图片里包含着句子，第一个人打出这个句子获得reward.

**建议间隔时间长一点。**

句子内容可以让别人投稿，或者是从cave里选出来纯文本无emoji的句子

**Comment by muderstar** [comment]
还有一个建议：假设这个群活跃度不高（一天没几个消息）直接不发送；反之如果活跃度很高那就减少发送间隔时间。

**Comment by muderstar** [comment]
以及这个似乎就是quickmath的简单版本。

**Comment by This-is-XiaoDeng** [comment]
之前 QuickMath 的机制已经被很多个群的群员或群管反馈烦人或刷屏了

**Comment by muderstar** [comment]
> 之前 QuickMath 的机制已经被很多个群的群员或群管反馈烦人或刷屏了

我觉得可以限制每个群里放几次这个信息，比如每天只放5次，随机时刻

**Comment by This-is-XiaoDeng** [comment]
@LzzKill 建议单开一个指令然后改成根据上句写下句

**Comment by muderstar** [comment]
_我觉得这个iss可以分为两个iss_

如果别人不想被spam，设置一个指令让间隔
时间变长或**极大减少**发送的次数

**Comment by muderstar** [comment]
要拆成两个iss吗？

**Comment by muderstar** [comment]
要分成两个iss吗？

一个优化quickmath和别的。

**Comment by This-is-XiaoDeng** [comment]
> 要分成两个iss吗？
> 
> 再开一个优化quickmath和别的。

您随意

**Comment by LzzKill** [comment]
报告，不会
